//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by openapi-gen. DO NOT EDIT.

package v1beta1

import (
	common "k8s.io/kube-openapi/pkg/common"
	spec "k8s.io/kube-openapi/pkg/validation/spec"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.BackendRefConfig":                schema_pkg_apis_negbinding_v1beta1_BackendRefConfig(ref),
		"k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.NetworkEndpointGroupBinding":     schema_pkg_apis_negbinding_v1beta1_NetworkEndpointGroupBinding(ref),
		"k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.NetworkEndpointGroupBindingSpec": schema_pkg_apis_negbinding_v1beta1_NetworkEndpointGroupBindingSpec(ref),
		"k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.RequestedNegRef":                 schema_pkg_apis_negbinding_v1beta1_RequestedNegRef(ref),
	}
}

func schema_pkg_apis_negbinding_v1beta1_BackendRefConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "BackendRefConfig specifies backendRef for the NetworkEndpointGroupBinding resource",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"group": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
					"kind": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
					"name": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
					"port": {
						SchemaProps: spec.SchemaProps{
							Default: 0,
							Type:    []string{"integer"},
							Format:  "int32",
						},
					},
				},
				Required: []string{"group", "kind", "name", "port"},
			},
		},
	}
}

func schema_pkg_apis_negbinding_v1beta1_NetworkEndpointGroupBinding(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type: []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.NetworkEndpointGroupBindingSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Default: map[string]interface{}{},
							Ref:     ref("k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.NetworkEndpointGroupBindingStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.NetworkEndpointGroupBindingSpec", "k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.NetworkEndpointGroupBindingStatus"},
	}
}

func schema_pkg_apis_negbinding_v1beta1_NetworkEndpointGroupBindingSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NetworkEndpointGroupBindingSpec is the spec for a NetworkEndpointGroupBinding resource",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"backendRef": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-validations": []interface{}{map[string]interface{}{"message": "BackendRef can't be changed", "rule": "oldSelf == self"}},
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "BackendRef references backend to which NEGs should be attached",
							Ref:         ref("k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.BackendRefConfig"),
						},
					},
					"networkEndpointGroups": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-map-keys": []interface{}{
									"name",
								},
								"x-kubernetes-list-type": "map",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "NetworkEndpointGroups references NEGs which should be managed by controller",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Default: map[string]interface{}{},
										Ref:     ref("k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.RequestedNegRef"),
									},
								},
							},
						},
					},
				},
				Required: []string{"backendRef", "networkEndpointGroups"},
			},
		},
		Dependencies: []string{
			"k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.BackendRefConfig", "k8s.io/ingress-gce/pkg/apis/negbinding/v1beta1.RequestedNegRef"},
	}
}

func schema_pkg_apis_negbinding_v1beta1_RequestedNegRef(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RequestedNegRef references NetworkEndpointGroups across cluster zones which should be managed by controller",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"name": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
					"subnet": {
						SchemaProps: spec.SchemaProps{
							Default: "",
							Type:    []string{"string"},
							Format:  "",
						},
					},
				},
				Required: []string{"name", "subnet"},
			},
		},
	}
}
